# Generated by Django 4.2.9 on 2024-06-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "sno",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="undefined", max_length=100, null=True
                    ),
                ),
                ("age", models.IntegerField(default=5, null=True)),
                (
                    "profile_img",
                    models.ImageField(
                        default="static/images/default.png",
                        null=True,
                        upload_to="static/images",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(default="undefined", max_length=100, null=True),
                ),
                (
                    "address",
                    models.CharField(default="undefined", max_length=100, null=True),
                ),
                (
                    "roll_no",
                    models.CharField(default="undefined", max_length=100, null=True),
                ),
                ("date_of_addmission", models.DateField(auto_now_add=True, null=True)),
                ("dob", models.DateField(auto_now_add=True, null=True)),
                (
                    "admission_no",
                    models.CharField(default="undefined", max_length=100, null=True),
                ),
                (
                    "about",
                    models.TextField(default="A student of XYZ school.", null=True),
                ),
                (
                    "fathers_name",
                    models.CharField(
                        db_index=True, default="undefined", max_length=500, null=True
                    ),
                ),
                (
                    "mothers_name",
                    models.CharField(
                        db_index=True, default="undefined", max_length=500, null=True
                    ),
                ),
                (
                    "phone_num",
                    models.CharField(default="xxxxxxxxxx", max_length=20, null=True),
                ),
                (
                    "phone_num_alt",
                    models.CharField(default="xxxxxxxxxx", max_length=20, null=True),
                ),
                (
                    "phone_gardian",
                    models.CharField(default="xxxxxxxxxx", max_length=20, null=True),
                ),
                ("isactive", models.BooleanField(default=True, null=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
    ]
