# Generated by Django 4.2.9 on 2024-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_student_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(default="undefined", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_no",
            field=models.CharField(
                db_index=True,
                default="undefined",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(default="undefined", max_length=100, null=True),
        ),
    ]
