# Generated by Django 4.2.9 on 2024-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manage_student_app",
            "0002_alter_student_address_alter_student_admission_no_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.CharField(
                db_index=True,
                default="anonymous",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
