# Generated by Django 4.2.9 on 2024-06-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_student_app", "0003_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_gardian",
            field=models.CharField(default="xxxxxxxxxx", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_num",
            field=models.CharField(default="xxxxxxxxxx", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_num_alt",
            field=models.CharField(default="xxxxxxxxxx", max_length=60, null=True),
        ),
    ]
